import { UqExt as Uq, assign } from './JkMe';
import * as Object from './Object.ui';
import * as ItemHistory from './ItemHistory.ui';
import * as OrderDetail from './OrderDetail.ui';
import * as OrderMain from './OrderMain.ui';
import * as ItemTitle from './ItemTitle.ui';
import * as PostTitle from './PostTitle.ui';
import * as ObjectUser from './ObjectUser.ui';
import * as ObjectStaff from './ObjectStaff.ui';
import * as ObjectPost from './ObjectPost.ui';
import * as ObjectCustomer from './ObjectCustomer.ui';
import * as ObjectPostItem from './ObjectPostItem.ui';
import * as Group from './Group.ui';
import * as DxOrderDetail from './DxOrderDetail.ui';
import * as DxOrderMain from './DxOrderMain.ui';
import * as UserTimezone from './UserTimezone.ui';
import * as UserObject from './UserObject.ui';
import * as PostItemHistory from './PostItemHistory.ui';
import * as PostItem from './PostItem.ui';
import * as IxPendingOrderAction from './IxPendingOrderAction.ui';
import * as IxOrderBoundTo from './IxOrderBoundTo.ui';
import * as IxPendingOrderItem from './IxPendingOrderItem.ui';
import * as GroupObject from './GroupObject.ui';
import * as UserSuperviseItem from './UserSuperviseItem.ui';
	
export function setUI(uq: Uq) {
	assign(uq, 'Object', Object);
	assign(uq, 'ItemHistory', ItemHistory);
	assign(uq, 'OrderDetail', OrderDetail);
	assign(uq, 'OrderMain', OrderMain);
	assign(uq, 'ItemTitle', ItemTitle);
	assign(uq, 'PostTitle', PostTitle);
	assign(uq, 'ObjectUser', ObjectUser);
	assign(uq, 'ObjectStaff', ObjectStaff);
	assign(uq, 'ObjectPost', ObjectPost);
	assign(uq, 'ObjectCustomer', ObjectCustomer);
	assign(uq, 'ObjectPostItem', ObjectPostItem);
	assign(uq, 'Group', Group);
	assign(uq, 'DxOrderDetail', DxOrderDetail);
	assign(uq, 'DxOrderMain', DxOrderMain);
	assign(uq, 'UserTimezone', UserTimezone);
	assign(uq, 'UserObject', UserObject);
	assign(uq, 'PostItemHistory', PostItemHistory);
	assign(uq, 'PostItem', PostItem);
	assign(uq, 'IxPendingOrderAction', IxPendingOrderAction);
	assign(uq, 'IxOrderBoundTo', IxOrderBoundTo);
	assign(uq, 'IxPendingOrderItem', IxPendingOrderItem);
	assign(uq, 'GroupObject', GroupObject);
	assign(uq, 'UserSuperviseItem', UserSuperviseItem);
}
export * from './JkMe';
